kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: helloworld-ws
  namespace: jboss-hello-world
  uid: bf9ee223-25db-46c2-9a25-ae37bd780621
  resourceVersion: '2401654'
  generation: 14
  creationTimestamp: '2022-09-16T19:50:46Z'
  labels:
    app: helloworld-ws
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    app: helloworld-ws
    deploymentconfig: helloworld-ws
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: helloworld-ws
        deploymentconfig: helloworld-ws
    spec:
      containers:
        - name: helloworld-ws
          image: >-
            image-registry.openshift-image-registry.svc:5000/jboss-hello-world/jboss64:1.2
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
            - containerPort: 9090
              protocol: TCP
            - containerPort: 9990
              protocol: TCP
          env:
            - name: TP_AMBIENTE
              value: dese
            - name: DB_DDL_AUTO
              value: none
            - name: TZ
              value: America/Fortaleza
            - name: http_proxy
              value: '10.15.15.36:9191'
            - name: https_proxy
              value: '10.15.15.36:9191'
            - name: DISABLE_EMBEDDED_JMS_BROKER
              value: 'true'
            - name: http.proxyHost
              value: 10.15.15.36
            - name: http.proxyPort
              value: '9090'
            - name: http.proxyHost
              value: 10.15.15.36
            - name: http.proxyPort
              value: '9090'
            - name: URL_SMTP
              value: '10.15.15.36'
            - name: EMAIL_REMETENTE
              value: naoresponda@teste.com.br
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler